import type {
  ActivityLog,
  AutomationJob,
  ContentItem,
  InstaAccount,
  ModerationItem,
  ProcessItem,
} from '@/lib/content-ops/types';

const iso = (offsetMin: number) =>
  new Date(Date.now() - offsetMin * 60_000).toISOString();

export const mockAccounts: InstaAccount[] = [
  {
    id: 'acc-1',
    name: '@studio.north',
    niche: 'Product design',
    status: 'active',
    platform: 'instagram',
    lastPostAt: iso(180),
    followers: 128400,
    engagementRate: 3.2,
    healthScore: 94,
  },
  {
    id: 'acc-2',
    name: '@fuelkitchen',
    niche: 'Food & beverage',
    status: 'warning',
    platform: 'instagram',
    lastPostAt: iso(720),
    followers: 45200,
    engagementRate: 1.9,
    healthScore: 71,
  },
  {
    id: 'acc-3',
    name: '@loopfit',
    niche: 'Fitness',
    status: 'active',
    platform: 'instagram',
    lastPostAt: iso(45),
    followers: 210300,
    engagementRate: 4.1,
    healthScore: 88,
  },
  {
    id: 'acc-4',
    name: '@archive.mag',
    niche: 'Editorial',
    status: 'paused',
    platform: 'instagram',
    lastPostAt: iso(10080),
    followers: 8900,
    engagementRate: 0.8,
    healthScore: 52,
  },
  {
    id: 'acc-5',
    name: '@signal.tech',
    niche: 'B2B SaaS',
    status: 'restricted',
    platform: 'instagram',
    lastPostAt: iso(2880),
    followers: 34000,
    engagementRate: 1.1,
    healthScore: 38,
  },
];

export const mockProcesses: ProcessItem[] = [
  {
    id: 'prc-101',
    title: 'Q2 reel batch — studio.north',
    description:
      'Generate hooks, shot list, and captions for 12 reels; legal review on claims.',
    status: 'running',
    priority: 'high',
    owner: 'M. Chen',
    createdAt: iso(4320),
    updatedAt: iso(25),
    startedAt: iso(120),
    dueAt: new Date(Date.now() + 2 * 86400_000).toISOString(),
    nextStep: 'Caption QA pass',
    tags: ['reels', 'legal'],
    dependencies: ['prc-099'],
  },
  {
    id: 'prc-099',
    title: 'Brand safety keyword refresh',
    status: 'done',
    priority: 'medium',
    owner: 'A. Okonkwo',
    createdAt: iso(9000),
    updatedAt: iso(8000),
    tags: ['moderation'],
  },
  {
    id: 'prc-112',
    title: 'Cross-account UGC ingestion',
    status: 'blocked',
    priority: 'critical',
    owner: 'J. Rivera',
    createdAt: iso(200),
    updatedAt: iso(15),
    nextStep: 'Unblock Meta token scope',
    tags: ['api', 'collector'],
    dependencies: [],
  },
  {
    id: 'prc-118',
    title: 'Weekly analytics digest',
    status: 'review',
    priority: 'low',
    owner: 'S. Patel',
    createdAt: iso(6000),
    updatedAt: iso(90),
    nextStep: 'Stakeholder sign-off',
    tags: ['reporting'],
  },
  {
    id: 'prc-120',
    title: 'Story templates — loopfit',
    status: 'pending',
    priority: 'medium',
    owner: 'M. Chen',
    createdAt: iso(45),
    updatedAt: iso(44),
    tags: ['stories'],
  },
  {
    id: 'prc-121',
    title: 'Failed publish retry queue',
    status: 'failed',
    priority: 'high',
    owner: 'Ops',
    createdAt: iso(300),
    updatedAt: iso(10),
    nextStep: 'Inspect publisher job acc-2',
    tags: ['publisher'],
  },
  {
    id: 'prc-122',
    title: 'New account onboarding checklist',
    status: 'draft',
    priority: 'low',
    owner: 'A. Okonkwo',
    createdAt: iso(20),
    updatedAt: iso(20),
    tags: ['onboarding'],
  },
];

export const mockJobs: AutomationJob[] = [
  {
    id: 'job-1',
    name: 'Collector — mentions & tags',
    type: 'collector',
    status: 'running',
    accountId: 'acc-1',
    lastRunAt: iso(3),
    nextRunAt: new Date(Date.now() + 12 * 60_000).toISOString(),
    successRate: 99.2,
    errorRate: 0.8,
  },
  {
    id: 'job-2',
    name: 'Caption generator v3',
    type: 'generator',
    status: 'queued',
    accountId: 'acc-2',
    lastRunAt: iso(40),
    nextRunAt: new Date(Date.now() + 5 * 60_000).toISOString(),
    successRate: 96.4,
    errorRate: 3.6,
    lastError: 'Rate limit 429 — backing off',
  },
  {
    id: 'job-3',
    name: 'Publish window — EU morning',
    type: 'publisher',
    status: 'paused',
    accountId: 'acc-3',
    lastRunAt: iso(200),
    nextRunAt: undefined,
    successRate: 92.1,
    errorRate: 7.9,
  },
  {
    id: 'job-4',
    name: 'Scheduler — fuelkitchen',
    type: 'scheduler',
    status: 'success',
    accountId: 'acc-2',
    lastRunAt: iso(8),
    nextRunAt: new Date(Date.now() + 55 * 60_000).toISOString(),
    successRate: 100,
    errorRate: 0,
  },
  {
    id: 'job-5',
    name: 'DM triage — keywords',
    type: 'moderation',
    status: 'warning',
    accountId: 'acc-1',
    lastRunAt: iso(12),
    nextRunAt: new Date(Date.now() + 3 * 60_000).toISOString(),
    successRate: 88.0,
    errorRate: 12.0,
    lastError: '3 messages exceeded confidence threshold',
  },
  {
    id: 'job-6',
    name: 'Weekly rollup — all accounts',
    type: 'analytics',
    status: 'idle',
    accountId: 'acc-1',
    lastRunAt: iso(10080),
    nextRunAt: new Date(Date.now() + 4 * 86400_000).toISOString(),
    successRate: 100,
    errorRate: 0,
  },
  {
    id: 'job-7',
    name: 'Reel renderer — batch B',
    type: 'generator',
    status: 'failed',
    accountId: 'acc-5',
    lastRunAt: iso(60),
    successRate: 71.2,
    errorRate: 28.8,
    lastError: 'FFmpeg exit code 1 — corrupt asset',
  },
  {
    id: 'job-8',
    name: 'Comment sentiment scorer',
    type: 'moderation',
    status: 'blocked',
    accountId: 'acc-5',
    lastRunAt: iso(500),
    lastError: 'API policy change — awaiting approval',
  },
];

export const mockContent: ContentItem[] = [
  {
    id: 'cnt-1',
    accountId: 'acc-1',
    title: 'Desk setup — 15s hook',
    format: 'reel',
    stage: 'idea',
    caption: 'Draft notes only',
  },
  {
    id: 'cnt-2',
    accountId: 'acc-2',
    title: 'Menu drop — carousel',
    format: 'carousel',
    stage: 'generated',
    assetUrl: '/mock/asset-1.jpg',
  },
  {
    id: 'cnt-3',
    accountId: 'acc-3',
    title: 'Mobility flow — voiceover',
    format: 'reel',
    stage: 'review',
    scheduledAt: new Date(Date.now() + 86400_000).toISOString(),
  },
  {
    id: 'cnt-4',
    accountId: 'acc-1',
    title: 'Client case — static post',
    format: 'post',
    stage: 'approved',
  },
  {
    id: 'cnt-5',
    accountId: 'acc-2',
    title: 'Brunch promo — story set',
    format: 'story',
    stage: 'scheduled',
    scheduledAt: new Date(Date.now() + 3 * 3600_000).toISOString(),
  },
  {
    id: 'cnt-6',
    accountId: 'acc-3',
    title: 'Member spotlight',
    format: 'post',
    stage: 'published',
    publishedAt: iso(120),
  },
  {
    id: 'cnt-7',
    accountId: 'acc-5',
    title: 'Webinar clip',
    format: 'reel',
    stage: 'failed',
  },
];

export const mockLogs: ActivityLog[] = [
  {
    id: 'log-1',
    entityType: 'job',
    entityId: 'job-7',
    level: 'error',
    message: 'Job job-7 failed: FFmpeg exit code 1',
    timestamp: iso(58),
  },
  {
    id: 'log-2',
    entityType: 'system',
    entityId: 'sys',
    level: 'warning',
    message: 'Queue depth publisher_eu exceeded soft limit (240)',
    timestamp: iso(30),
  },
  {
    id: 'log-3',
    entityType: 'content',
    entityId: 'cnt-6',
    level: 'info',
    message: 'Published cnt-6 to acc-3',
    timestamp: iso(120),
  },
  {
    id: 'log-4',
    entityType: 'account',
    entityId: 'acc-5',
    level: 'warning',
    message: 'Health score dropped below 40 — flagged in overview',
    timestamp: iso(400),
  },
  {
    id: 'log-5',
    entityType: 'process',
    entityId: 'prc-101',
    level: 'info',
    message: 'Process prc-101 advanced: running',
    timestamp: iso(25),
  },
  {
    id: 'log-6',
    entityType: 'system',
    entityId: 'sys',
    level: 'info',
    message: 'Nightly backup completed',
    timestamp: iso(500),
  },
  {
    id: 'log-7',
    entityType: 'job',
    entityId: 'job-2',
    level: 'warning',
    message: 'Retry scheduled for generator acc-2',
    timestamp: iso(40),
  },
];

export const mockModeration: ModerationItem[] = [
  {
    id: 'mod-1',
    accountId: 'acc-2',
    type: 'comment',
    content: 'Is this gluten free? Need for kid party Saturday',
    status: 'open',
    author: 'user_48291',
    createdAt: iso(12),
  },
  {
    id: 'mod-2',
    accountId: 'acc-1',
    type: 'dm',
    content: 'Collab rates for 50k design account?',
    status: 'reviewing',
    author: 'creator.mail',
    createdAt: iso(45),
  },
  {
    id: 'mod-3',
    accountId: 'acc-3',
    type: 'comment',
    content: 'Link broken in bio',
    status: 'resolved',
    author: 'runner_22',
    createdAt: iso(200),
  },
  {
    id: 'mod-4',
    accountId: 'acc-5',
    type: 'comment',
    content: 'This looks like spam funnel',
    status: 'flagged',
    author: 'mod_internal',
    createdAt: iso(5),
  },
];

export function accountById(id: string): InstaAccount | undefined {
  return mockAccounts.find((a) => a.id === id);
}

export function processById(id: string): ProcessItem | undefined {
  return mockProcesses.find((p) => p.id === id);
}
